<hr>
<b>CÔNG TY CỔ PHẦN VIKING VIỆT NAM</b>
<br>VPGD: Tòa Bắc Rice City, KĐT Tây Nam Linh Đàm, quận Hoàng Mai, Hà Nội
<br>Điện thoại: 024.3864.5599
<p>
<b>NHÀ MÁY TẠI SÓC SƠN</b>
<br>Địa chỉ: Xã Phú Minh, huyện Sóc Sơn, Hà Nội
<br>Email: info@ViKingJsc.com; Website: <a href="http://www.VikingJsc.com">www.VikingJsc.com</a>
<br>Hotline: 0982.312.373 (Mr. Quang Hùng)
<br>Số ĐKKD: 0106610502. Sở Kế hoạch Đầu tư Hà Nội cấp ngày cấp: 30-07-2014.