<!DOCTYPE html>  <!--  very important for responsive tables -->

<head>

<title>Công ty Cổ phần Viking - Viking JSC
</title>

<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="web-styles.css" rel="stylesheet" type="text/css" media="all">

</head>

<!-- Responsible table 
<table class="mv1" border=1 style="border-collapse: collapse;" width="99%">
<thead class="mv1"><td>First Name<td>Last Name<td>Job Title</thead>
<tr><td class="mv1">John<td class="mv1">Smith<td class="mv1">Chief Sandwich Eater
<tr><td class="mv1">Linda<td class="mv1">Brown<td class="mv1">Crimefighter Sorta
</table>
-->
