
<img src="./img/header-desktop.jpg" style="cursor:pointer" onClick="window.location.href='./';">

<br><table border=0 bgcolor=#0000FF width="100%">
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./">&nbsp;HOME&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td>
  <ul>
    <li>
      <a href="#">&nbsp;GIỚI THIỆU&nbsp;</a>
      <ul>
        <li><a href="./gt-nha-may-viking.html">&nbsp;Nhà máy Viking&nbsp;</a></li>
        <li><a href="./gt-nhan-luc-cong-ty.html">&nbsp;Nhân lực công ty&nbsp;</a></li>
        <li><a href="./gt-ho-so-kinh-nghiem.html">&nbsp;Hồ sơ kinh nghiệm&nbsp;</a></li>
        <li><a href="./gt-so-do-to-chuc.html">&nbsp;Sơ đồ tổ chức&nbsp;</a></li>
        <li><a href="./gt-van-hoa-cong-ty.html">&nbsp;Văn hóa công ty&nbsp;</a></li>
      </ul>
    </li>
  </ul>
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./nha-thep-tien-che.html">&nbsp;NHÀ THÉP TIỀN CHẾ&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./thi-cong-xay-dung.html">&nbsp;THI CÔNG XÂY DỰNG CÔNG TRÌNH&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./he-san.html">&nbsp;HỆ SÀN&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./thiet-bi-nang-ha.html">&nbsp;THIẾT BỊ NÂNG HẠ&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./du-an-tieu-bieu.html">&nbsp;DỰ ÁN TIÊU BIỂU&nbsp;
<td>&nbsp;&nbsp;&nbsp;&nbsp;<td><a href="./lien-he.html">&nbsp;LIÊN HỆ&nbsp;
</table>
